Add echo
Signed-off-by: Sanjula Ganepola <Sanjula.Ganepola@ibm.com>

diff --git a/.github/workflows/pr.yaml b/.github/workflows/pr.yaml
--- a/.github/workflows/pr.yaml
+++ b/.github/workflows/pr.yaml
@@ -123,4 +123,6 @@ jobs:
 
       - name: Check Test Result
         if: steps.test.outcome == 'failure'
-        run: exit 1
+        run: |
+          echo "Tests failed. Check logs for details."
+          exit 1
